# Related files: backend/main.py
# Location: docker-compose.yml

version: '3.8'

services:
  vector-db:
    image: qdrant/qdrant:latest
    container_name: vector-db
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped

  lm-studio:
    # Note: LM Studio doesn't have official Docker image
    # You need to run LM Studio locally on port 1234
    # This is just a placeholder for documentation
    image: alpine
    container_name: lm-studio-placeholder
    command: echo "Please run LM Studio locally on port 1234"
    restart: "no"